### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'parameterized_json'

### ISSUE THREAD

**Issue by fluancefg** [dalibo/powa#73] opened 2016-04-20 10:16 UTC
Hello,

I've installed the latest version of powa-web (3.0.2) on archlinux and I get the following error when I try to get the detail of a query: 500: Internal Server Error

And in the log:

`Uncaught exception GET /database/granulaoperate/query/4253884743/overview/ (127.0.0.1)
Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/alarm/powa-web-3.0.2/powa/dashboards.py", line 37, in get
        param_dashboard = self.dashboard.parameterized_json(self, **params)
    AttributeError: 'NoneType' object has no attribute 'parameterized_json'`

python 3.5.1-2
python-psycopg2 2.6.1-2
python-sqlalchemy 1.0.12-1
python-tornado 4.3.0-1

**Comment by rdunklau** [comment] 2016-04-21 13:25
Hello.

This is probably a duplicate of https://github.com/dalibo/powa-web/issues/13 which has already been fixed, but not yet released.

Can you confirm using the git version ?

Thank you for the report.

**Comment by fluancefg** [comment] 2016-04-21 14:01
Sorry, I have missed that one.

I have replaced the file powa/query.py with the one on github and it works flawlessly.

Thank you.

**Closed** 2016-04-21 14:21 UTC
